### PR TITLE
Add missing rcsId and contributorId to Tag model.

### PR DESCRIPTION
**Pull request by LATaylor-guardian**

### CODE REVIEW

**Comment by cb372** [comment]
👍

Let's have filtering in concierge to only expose these 2 fields on the internal tier.

**Comment by LATaylor-guardian** [comment]
> Let's have filtering in concierge to only expose these 2 fields on the internal tier.

@cb372 Why do we need to provide new behaviour? These fields existed before and are not new fields as such?

**Comment by cb372** [comment]
Just because they are internal fields, only needed by RCS these days, and we don't want anyone else to start depending on them.

**Comment by LATaylor-guardian** [comment]
> Just because they are internal fields, only needed by RCS these days, and we don't want anyone else to start depending on them.

Okay, will add.

**Pull request merged**
