### PR TITLE
Support decoding of Boolean from JSON strings ("true"/"false")

### PR DESCRIPTION
**Pull request by cb372**
This is to fix the boolean block attributes (keyEvent, summary, pinned)

### CODE REVIEW

**Comment by tomrf1** [comment]
👍

**Comment by LATaylor-guardian** [comment]
@johnduffell

**Comment by LATaylor-guardian** [comment]
👍 Let central prod know once this is out. :)

**Comment by johnduffell** [comment]
brilliant, thanks!

**Pull request merged**
