### PR TITLE
Add internal revision field to Crier's model

### PR DESCRIPTION
**Pull request by oilnam**
I should've merged this before releasing the new model, oops. Sorry.

### CODE REVIEW

**Comment by cb372** [comment]
Why not add the `internalRevision` field to the `RetrievableContent` struct instead? It only makes sense for content, not other types we might add in the future.

**Comment by LATaylor-guardian** [comment]
Yes, It will need to be available in the `Content ` and `RetrievableContent`struct. In theory, nothing else should need to be added to the `Event` struct. It's purposely kept quite generic.

**Comment by oilnam** [comment]
@LATaylor-guardian I see your point. I added it to `RetrievableContent` only, since we can already get it from inside `Content` (I added it in a previous PR).

**Comment by cb372** [comment]
👍

**Comment by LATaylor-guardian** [comment]
👍

**Pull request merged**
